# # Simulating a Gibbs sampler
# This is full-density-matrix Lindbladian evolution, with continuous generator
# time. It is not a sampled quantum-jump trajectory or a channel step count.
using QuantumFurnace

H = pauli_hamiltonian(2, [
    -1.0 => (1 => :Z, 2 => :Z),
    -0.7 => (1 => :X,),
    -0.7 => (2 => :X,),
])
result = simulate_gibbs(H; beta_phys=0.8,
    times=range(0, 20; length=21), epsilon=1e-3, diagnostics=:strict)
@assert result.trajectory.all_converged
@assert result.trajectory.trace_norms ≈ 2result.trajectory.distances
@assert last(result.trajectory.distances) < result.convergence.epsilon
@assert result.spectrum.reliability == :pass
println("Numerical evolution completed: ", result.trajectory.all_converged)
println("Time    Distance to Gibbs")
for i in 1:5:length(result.trajectory.t)
    println(rpad(string(round(result.trajectory.t[i]; digits=1)), 8),
        round(result.trajectory.distances[i]; sigdigits=3))
end

# These numbers are generated by the code above, not pasted example output.
# Distance to Gibbs ranges from zero (the target state) to one (maximally
# distinguishable normalised states). Read down the table to see how close this
# initial state gets during the requested time interval. The times use the
# generator clock fixed by the jump amplitudes, not wall-clock seconds.
# `true` reports successful numerical propagation, not arrival at Gibbs.

# Input/output states use the computational basis by default. The initial state
# is |+><+| tensor power. Saved intermediate states are off by default; request
# save_states=true with a suitable max_saved_bytes cap if needed.
println("Convergence assessment: ", result.convergence.status)

# The assessment applies to this trajectory and its requested accuracy. A small
# final distance demonstrates closeness for this run, not every initial state.
# `reached_threshold` means the run reached its requested distance of `0.001`.

# The independent spectral policy uses its own operator starts. A small Ritz
# residual does not rule out missed modes; inspect reliability and coverage.
println("Spectral reliability: ", result.spectrum.reliability)

# Reliability describes the available spectral evidence. It is separate from
# whether the trajectory solver completed successfully.
# `pass` means the independent checks agree with the complete small-system
# reference. `diagnostics=:strict` enables that reference for this tiny example.

# Save the combined result as versioned data, then continue from its final state.
# A fresh workspace is rebuilt. The continuation
# segment starts at zero additional time, and records the preceding time origin.
continuation = mktempdir() do directory
    path = save_result(result, joinpath(directory, "gibbs.bson"))
    restored = load_result(path)
    @assert restored.trajectory.rho_final ≈ result.trajectory.rho_final
    simulate_gibbs(restored; times=[0.0, 0.1], diagnostics=:quick)
end
@assert continuation.provenance.resume_time_origin ≈ last(result.trajectory.t)
println("Resumed from generator time: ", continuation.provenance.resume_time_origin)
println("Continuation completed: ", continuation.trajectory.all_converged)
println("Distance after continuation: ", round(last(continuation.trajectory.distances); sigdigits=3))

# The saved state starts a new evolution segment. The time origin confirms where
# it joins the preceding run; the distance shows the state after that extra time.

# ## Finite channel steps
# Select the `run_thermalize` backend explicitly. This applies the
# implemented weak-measurement channel, including its coherent step.
# CKG is selected explicitly because DLL finite channels are not implemented.
channel = simulate_gibbs(H; sim=Thermalize(), construction=KMS(),
    beta_phys=0.8, delta=0.01, steps=5000, epsilon=1e-3, save_states=true,
    channel_options=(save_every=1000,))
@assert channel.trajectory.channel_steps == [0, 1000, 2000, 3000, 4000, 5000]
@assert channel.trajectory.states[end] ≈ channel.trajectory.rho_final
@assert channel.spectrum.reliability == :not_run
@assert last(channel.trajectory.distances) < channel.convergence.epsilon
println("Recorded channel steps: ", channel.trajectory.channel_steps)
println("Completed channel steps: ", channel.trajectory.completed_steps)
println("Final distance to Gibbs: ", round(last(channel.trajectory.distances); sigdigits=3))
println("Reached the requested distance < 0.001: ",
    last(channel.trajectory.distances) < channel.convergence.epsilon)

# Intermediate states are saved every 1000 steps. The final distance is below
# `0.001`, so this channel run also reaches the requested accuracy. The reported
# distance checks the actual state; completing a given step count alone would
# not establish that. Spectral analysis is not part of this channel example.

# Lindblad evolution computes exp(t*L)rho0: method=:krylov uses successive
# Arnoldi exponential actions, while method=:predictor reuses captured modes.
# Finite channel evolution instead applies E_delta repeatedly. These targets
# need not agree at finite delta. Times for channel runs must lie on the delta
# grid; integer steps avoid rounding ambiguity. One sweep applies every source.
# The clock includes the backend rate normalisation recorded in provenance.
# Hamiltonian rescaling does not independently rescale delta.

# channel_options=(jump_selection=:random, seed=42) selects one source per
# outer step with the backend's default probability compensation. Each returned
# density matrix is conditioned on those source choices; it is not the average
# over source histories or a sampled measurement-outcome trajectory.
# Channel diagnostics check sampled states; spectrum, stationarity and KMS
# checks are explicitly not_run. Crossing epsilon is only an observed crossing.
# The finite channel can have a bias from Gibbs even if its ideal generator
# fixes Gibbs. Source rates must obey the channel's operator-normalisation bound.

# Channel results support save_result/load_result as evidence. Automatic
# Workspace(result) and simulate_gibbs(result; times=...) reconstruction reject.
# Continue using the same original inputs and the returned final density matrix:
next_channel = simulate_gibbs(H; sim=Thermalize(), construction=KMS(),
    beta_phys=0.8, delta=0.01, steps=2, rho0=channel.trajectory.rho_final)
@assert next_channel.trajectory.completed_steps == 2
println("Additional channel steps completed: ", next_channel.trajectory.completed_steps)
println("Distance after additional steps: ", round(last(next_channel.trajectory.distances); sigdigits=3))
